version: '2'

services:

  ca.goverment.example.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-goverment
      - FABRIC_CA_SERVER_TLS_ENABLED=true
    ports:
      - "7054:7054"
    # command: sh -c 'fabric-ca-server start -c /etc/hyperledger/fabric-ca-server-config/ca-server-goverment.yaml -b admin:adminpw -d'
    command: sh -c 'fabric-ca-server start 
                  -c /etc/hyperledger/fabric-ca-server-config/ca-server-goverment.yaml
                  --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.goverment.example.com-cert.pem 
                  --ca.keyfile /etc/hyperledger/fabric-ca-server-config/195d22021822384d456d7acfb732b93ae8abb6945af67078abc5eb78d2163c24_sk 
                  --tls.certfile /etc/hyperledger/fabric-ca-server-config/ca.goverment.example.com-cert.pem 
                  --tls.keyfile /etc/hyperledger/fabric-ca-server-config/195d22021822384d456d7acfb732b93ae8abb6945af67078abc5eb78d2163c24_sk 
                  -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/goverment.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerGoverment
