#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

services:

  ca.goverment.example.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-goverment
      - FABRIC_CA_SERVER_TLS_ENABLED=true
    ports:
      - "7054:7054"
    # command: sh -c 'fabric-ca-server start -c /etc/hyperledger/fabric-ca-server-config/ca-server-goverment.yaml -b admin:adminpw -d'
    command: sh -c 'fabric-ca-server start 
                  -c /etc/hyperledger/fabric-ca-server-config/ca-server-goverment.yaml
                  --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.goverment.example.com-cert.pem 
                  --ca.keyfile /etc/hyperledger/fabric-ca-server-config/195d22021822384d456d7acfb732b93ae8abb6945af67078abc5eb78d2163c24_sk 
                  --tls.certfile /etc/hyperledger/fabric-ca-server-config/ca.goverment.example.com-cert.pem 
                  --tls.keyfile /etc/hyperledger/fabric-ca-server-config/195d22021822384d456d7acfb732b93ae8abb6945af67078abc5eb78d2163c24_sk 
                  -b admin:adminpw -d'
    volumes:
      - ./channel/crypto-config/peerOrganizations/goverment.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerGoverment

  ca.airlines.example.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-airlines
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.airlines.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/27ba8bbf74f1b0a1dabc3ed54b380e47c60620ba5eb3ac729fb60fb648ed7eaf_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.airlines.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/27ba8bbf74f1b0a1dabc3ed54b380e47c60620ba5eb3ac729fb60fb648ed7eaf_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start 
                    -c /etc/hyperledger/fabric-ca-server-config/ca-server-airlines.yaml
                    -b admin:adminpw -d'
    volumes:
      - ./channel/crypto-config/peerOrganizations/airlines.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerAirlines

  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/crypto/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/crypto/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/crypto/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt, /etc/hyperledger/crypto/peerGoverment/tls/ca.crt, /etc/hyperledger/crypto/peerAirlines/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./channel:/etc/hyperledger/configtx
        - ./channel/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/:/etc/hyperledger/crypto/orderer
        - ./channel/crypto-config/peerOrganizations/goverment.example.com/peers/peer0.goverment.example.com/:/etc/hyperledger/crypto/peerGoverment
        - ./channel/crypto-config/peerOrganizations/airlines.example.com/peers/peer0.airlines.example.com/:/etc/hyperledger/crypto/peerAirlines

  peer0.goverment.example.com:
    container_name: peer0.goverment.example.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.goverment.example.com
      - CORE_PEER_LOCALMSPID=GovermentMSP
      - CORE_PEER_ADDRESS=peer0.goverment.example.com:7051
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - ./channel/crypto-config/peerOrganizations/goverment.example.com/peers/peer0.goverment.example.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - orderer.example.com

  peer0.airlines.example.com:
    container_name: peer0.airlines.example.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.airlines.example.com
      - CORE_PEER_LOCALMSPID=AirlinesMSP
      - CORE_PEER_ADDRESS=peer0.airlines.example.com:7051
    ports:
      - 8051:7051
      - 8053:7053
    volumes:
        - ./channel/crypto-config/peerOrganizations/airlines.example.com/peers/peer0.airlines.example.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - orderer.example.com

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.goverment.example.com:7051
      - CORE_PEER_LOCALMSPID=GovermentMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/goverment.example.com/peers/peer0.goverment.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/goverment.example.com/peers/peer0.goverment.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/goverment.example.com/peers/peer0.goverment.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/goverment.example.com/users/Admin@goverment.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./channel/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        # - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel
    depends_on:
      - orderer.example.com
      - peer0.goverment.example.com
      - peer0.airlines.example.com