---
name: "borders-control-network"

x-type: "hlfv1"

description: "Borders Control Network"
version: "1.0"

channels:
  mychannel:
    orderers:
      - orderer.example.com

    peers:
      peer0.goverment.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer0.airlines.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

    chaincodes:
      - mycc:v0

organizations:
  Goverment:
    mspid: GovermentMSP
    peers:
      - peer0.goverment.example.com
    certificateAuthorities:
      - ca-goverment
    adminPrivateKey:
      path: artifacts/channel/crypto-config/peerOrganizations/goverment.example.com/users/Admin@goverment.example.com/msp/keystore/aef8a7e7db09e25693ae42e5f98863413f749dbfa2f2d203fe5d3226dbdf8ace_sk
    signedCert:
      path: artifacts/channel/crypto-config/peerOrganizations/goverment.example.com/users/Admin@goverment.example.com/msp/signcerts/Admin@goverment.example.com-cert.pem

  Airlines:
    mspid: AirlinesMSP
    peers:
      - peer0.airlines.example.com
    certificateAuthorities:
      - ca-airlines
    adminPrivateKey:
      path: artifacts/channel/crypto-config/peerOrganizations/airlines.example.com/users/Admin@airlines.example.com/msp/keystore/8ea1124601e9b5a88e32d6cd098f5f00478fe4066862f53c5742c342024d67f2_sk
    signedCert:
      path: artifacts/channel/crypto-config/peerOrganizations/airlines.example.com/users/Admin@airlines.example.com/msp/signcerts/Admin@airlines.example.com-cert.pem

orderers:
  orderer.example.com:
    url: grpcs://localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer.example.com
      grpc-max-send-message-length: 15
    tlsCACerts:
      path: artifacts/channel/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt

peers:
  peer0.goverment.example.com:
    url: grpcs://localhost:7051
    eventUrl: grpcs://localhost:7053
    grpcOptions:
      ssl-target-name-override: peer0.goverment.example.com
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/goverment.example.com/peers/peer0.goverment.example.com/tls/ca.crt

  peer0.airlines.example.com:
    url: grpcs://localhost:8051
    eventUrl: grpcs://localhost:8053
    grpcOptions:
      ssl-target-name-override: peer0.airlines.example.com
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/airlines.example.com/peers/peer0.airlines.example.com/tls/ca.crt

certificateAuthorities:
  ca-goverment:
    url: https://localhost:7054
    httpOptions:
      verify: false
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/goverment.example.com/ca/ca.goverment.example.com-cert.pem
  # registrar:
  #   - enrollId: admin
  #     enrollSecret: adminpw
    caName: ca-goverment

  ca-airlines:
    url: https://localhost:8054
    httpOptions:
      verify: false
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/airlines.example.com/ca/ca.airlines.example.com-cert.pem
  # registrar:
  #   - enrollId: admin
  #     enrollSecret: adminpw
    caName: ca-airlines
